### PR TITLE
Added implementation for get_optics method

### PR DESCRIPTION
**Pull request by narJH27**
Implements https://github.com/napalm-automation/napalm-base/issues/56

### CODE REVIEW

**Comment by narJH27** [comment]
@dbarrosop Any idea why my test fails?

**Comment by mirceaulinic** [comment]
@narJH27 You need to cleanup your mock data (i.e. remove Junos-specific namespaces from the XML).

**Comment by mirceaulinic** [comment]
@narJH27 also, the mock you provided is truncated. A complete XML must begin with the following lines:

``` xml
<rpc-reply>
    <interface-information>
        <physical-interface>
            <name>xe-1/0/0</name>
            <optics-diagnostics>
```

**Comment by narJH27** [comment]
@mirceaulinic Not sure what you mean by Junos-specific namespaces? Also, all the other mock data files, do not begin with:

```
<rpc-reply>
    <interface-information>
        <physical-interface>
            <name>xe-1/0/0</name>
            <optics-diagnostics>
```

I have compared the mock outputs with what the device returns, and it seems to me as though the mock data is identical to the output returned by the device. Can you please explain exactly what you mean here?

**Comment by mirceaulinic** [comment]
@narJH27 

For example:

``` xml
junos:celsius="45.2"
```

from line 7 in your mock data

``` xml
<module-temperature junos:celsius="45.2">45 degrees C / 113 degrees F</module-temperature>
```

do you see it?

Is a qualified attribute from the Junos namespace.

**Comment by mirceaulinic** [comment]
@narJH27 

> Also, all the other mock data files, do not begin with:

Please read more carefully my suggestions before replying: https://github.com/napalm-automation/napalm-junos/pull/34#issuecomment-235112588

> A complete XML must begin with the following lines:

They don't and they should. Questions?

**Comment by narJH27** [comment]
@mirceaulinic Thanks for the help!

**Comment by narJH27** [comment]
@dbarrosop please merge this PR when you have a chance! :)

**Pull request merged**
