### PR TITLE
WIP: Implement `get_network_instances`

### PR DESCRIPTION
**Pull request by mirceaulinic**
<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

### CODE REVIEW

**Comment by dbarrosop** [comment]
pylama is not happy with you : )

**Comment by mirceaulinic** [comment]
@dbarrosop did you have a look at the code - I was thinking to move some static hashmaps/globals in a separate class `JunOSGlobals`. Does this make sense to you?

**Comment by dbarrosop** [comment]
Yeah, I saw it, I was thinking about it. I think it makes more sense to have a `constants.py` file. We could have one on `napalm-base` for constants that might be good for all the drivers, ie, timeout. And then have a constants file on each driver. Something like:

```
napalm-junos/constants.py
---------------------------
from napalm_base.constants import *

THIS_IS_A_JUNOS_CONSTANT = 'blah'
```

And then:

```
napalm_junos.py
----------------

import constants as c

c.MY_GLOBAL_CONSTANT # (comes from the from napalm_base.constants import *)
c.THIS_IS_A_JUNOS_CONSTANT
```

It also has the benefit that if we need it, we could override `MY_GLOBAL_CONSTANT` on a particular driver by just adding it to the driver-specific constant files.

**Comment by mirceaulinic** [comment]
Yes, that looks good @dbarrosop!

**Comment by mirceaulinic** [comment]
For the record - submitted this PR according to the discussion above: https://github.com/napalm-automation/napalm-base/pull/149

**Comment by mirceaulinic** [comment]
I've rescheduled this one for 0.6.0 - can't make it this week when I plan to release 0.5.0.

**Pull request closed without merging**
