### PR TITLE
Merging develop into master for the new testing framework

### PR DESCRIPTION
**Pull request by mirceaulinic**

### CODE REVIEW

**Comment by dbarrosop** [comment]
Same here, why merge into master without releasing?

**Comment by mirceaulinic** [comment]
Only to reduce the size of the PR when merged, as the testing framework migration is pretty big - but we can leave it open right now and commits pushed into ```develop``` will be here as well.

**Comment by dbarrosop** [comment]
Let's leave it open, when merging devel into master i mostly care about the tests passing anyway. The actual PR validates are done incrementally with each new addition anyway so no need of checking the base code yet again : )

**Comment by dbarrosop** [comment]
Is this one ready for merge and release?

**Comment by mirceaulinic** [comment]
Mm not yet - I would like to fix #84 firstly and eventually try an implementation for #81 (if I can't do it today, I'll leave it for next week).

**Review by dbarrosop — DISMISSED** [review]

**Comment by dbarrosop** [comment]
Let's merge #89 first.

**Pull request merged**
