### PR TITLE
Add get_probes_config() and get_probes_results()

### PR DESCRIPTION
**Pull request by mirceaulinic**
This is not gonna work: I need to add the testers in .travis.yml but I cannot since the package napalm_base does not contain the tests base (even after merge).
Thus either after merge you need to create a new release of napalm_base :-1: 
Either in travis specify to clone napalm_base and install the develop version.

### CODE REVIEW

**Comment by mirceaulinic** [comment]
I think we can accept this hack: #7. What do you think?

**Comment by dbarrosop** [comment]
Can you enable the test in travis? You might have to rebase to include the hack.

**Comment by mirceaulinic** [comment]
JunOS implementation for https://github.com/napalm-automation/napalm-base/pull/9. Can be merged anytime (if not conflicts in .travis.yml)

**Comment by mirceaulinic** [comment]
Check fails due to: https://github.com/napalm-automation/napalm-base/pull/15

**Pull request merged**
