### PR TITLE
Adds optional_arg for enabling keepalives.

### PR DESCRIPTION
**Pull request by zachmoody**
<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

Had a quick discussion with @mirceaulinic about adding an optional_arg that's passed to Paramiko's `set_keepalive()`. Here's a pretty quick pass at some working code. If I need some tests or refactoring let me know. Thanks!

### CODE REVIEW

**Comment by dbarrosop** [comment]
Could you open a PR on the main `napalm` repo and link it here to document this optional_arg, please?

Thanks!

**Comment by mirceaulinic** [comment]
I'm very surprised that ncclient does not set a keepalive by default. We should probably replicate this for all devices having SSH-based connection.

Would you agree having a default value for the `keepalive`, as for `timeout`, say 30 seconds or so?

**Comment by dbarrosop** [comment]
Sounds sane to me.

**Review by mirceaulinic — APPROVED** [review]
LGTM.

**Comment by zachmoody** [comment]
I had a look at OpenSSH's stance on keepalives and they're disabled by default as well. Maybe parity with that was what Paramiko, ncclient, etc. were going for. Made a couple more commits to set a default value. Will have a PR raised on napalm-base to get this in all applicable drivers shortly.

**Comment by mirceaulinic** [comment]
Thanks @zachmoody

**Comment by zachmoody** [comment]
PR for doc change is https://github.com/napalm-automation/napalm/pull/372

**Comment by mirceaulinic** [comment]
This will be delayed a bit due to other bugfixes to be addresses in the next release.
I hope to have the time for them this week or early next week.

**Pull request merged**
