### PR TITLE
JunOS: New struct out for get_bgp_neighbors_detail

### PR DESCRIPTION
**Pull request by mirceaulinic**
Ref: https://github.com/napalm-automation/napalm-base/pull/49 and https://github.com/napalm-automation/napalm-base/pull/51

### CODE REVIEW

**Comment by dbarrosop** [comment]
The test seems to be failing.

**Comment by mirceaulinic** [comment]
They need the base pull request merged first.

**Comment by dbarrosop** [comment]
Ok. I just merged them and restarted the build.

**Comment by dbarrosop** [comment]
Works : )

**Pull request merged**
