### PR TITLE
Require junos-eznc>=2.1.3

### PR DESCRIPTION
**Pull request by mirceaulinic**
To make sure we avoid issues like https://github.com/napalm-automation/napalm-junos/issues/152
Solved via https://github.com/Juniper/py-junos-eznc/pull/721 included in junos-eznc 2.1.3.

### CODE REVIEW

**Comment by ktbyers** [comment]
Why are the unit tests failing?

The change looked fine, but we need to fix the unit tests failing.

**Comment by mirceaulinic** [comment]
That's very strange. it's failing under `test_get_lldp_neighbors_detail/normal` and 

```
E           IOError: Couldn't find file with mocked data: /home/travis/build/napalm-automation/napalm-junos/test/unit/mocked_data/test_get_lldp_neighbors_detail/normal/get-lldp-interface-neighbors.xml
```

@dbarrosop any idea why? So bizarre, isn't it?

It is also failing `test_get_bgp_neighbors_detail/normal`, although it didn't previously... I will check this one tomorrow.

**Comment by ktbyers** [comment]
@mirceaulinic Yes, I see the last commit failed here:

https://github.com/napalm-automation/napalm-junos/commits/develop

Although the PR it didn't look like it failed? (I looked at it pretty quickly).

**Comment by mirceaulinic** [comment]
No, it didn't fail... Weird.

**Pull request merged**
