### PR TITLE
JunOS: Add traceroute()

### PR DESCRIPTION
**Pull request by mirceaulinic**
https://github.com/napalm-automation/napalm-base/pull/17

### CODE REVIEW

**Comment by dbarrosop** [comment]
I merged `napalm-base` and re-run the test. However, they are still failing, can you check?

**Comment by dbarrosop** [comment]
There seems to be some conflicts as well.

**Comment by mirceaulinic** [comment]
Being a non-standard RPC request, the test class gave me some headaches. At least I took this chance to make slight changes in the fake callers.
As for IOS-XR, this one needs https://github.com/napalm-automation/napalm-base/pull/20 merged a priori.

**Comment by dbarrosop** [comment]
The test is still failing, could you check?

**Comment by dbarrosop** [comment]
Disregard, this one is good.

**Pull request merged**
