### PR TITLE
Solve #112

### PR DESCRIPTION
**Pull request by mirceaulinic**
The tests will fail as https://github.com/napalm-automation/napalm-base/pull/185 is pending for merge and release.

### CODE REVIEW

**Comment by dbarrosop** [comment]
There are a few weird errors.

**Comment by mirceaulinic** [comment]
@dbarrosop 

```
E   ConftestImportFailure: AttributeError("'module' object has no attribute 'TRACEROUTE_VRF'",)
E     File "/home/travis/build/napalm-automation/napalm-junos/.tox/py27/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 216, in load_module
E       py.builtin.exec_(co, mod.__dict__)
E     File "/home/travis/build/napalm-automation/napalm-junos/.tox/py27/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
E       exec2(obj, globals, locals)
E     File "<string>", line 7, in exec2
E     File "/home/travis/build/napalm-automation/napalm-junos/test/unit/conftest.py", line 9, in <module>
E       from napalm_junos import junos
E     File "/home/travis/build/napalm-automation/napalm-junos/napalm_junos/__init__.py", line 21, in <module>
E       from napalm_junos.junos import JunOSDriver  # noqa
E     File "/home/travis/build/napalm-automation/napalm-junos/napalm_junos/junos.py", line 51, in <module>
E       class JunOSDriver(NetworkDriver):
E     File "/home/travis/build/napalm-automation/napalm-junos/napalm_junos/junos.py", line 1199, in JunOSDriver
E       vrf=C.TRACEROUTE_VRF):
```

Are because the attribute `TRACEROUTE_VRF` does not exist in `napalm-base` as https://github.com/napalm-automation/napalm-base/pull/185 has to be merged and a new version released first.

**Comment by dbarrosop** [comment]
Ok, let me fix a few PRs I have pending for the `validate` feature and I will release a new version.

**Comment by mirceaulinic** [comment]
No, please don't rush this. We firstly need to have the implementation on all drivers as this is an API change. So far we only have junos, xr and eos - almost. Still need pluribus and ios.

**Pull request merged**
