### PR TITLE
adding coveralls

### PR DESCRIPTION
**Pull request by fooelisa**
we could add this to the modules now and re-do as part of the transition to the new testing framework

### CODE REVIEW

**Review by mirceaulinic — APPROVED** [review]
Sounds good to me. I will try to integrate with the new testing framework at the beginning of October and will ping you then to update this file :)

**Comment by mirceaulinic** [comment]
WTF still computing coverage after 19 minutes??

**Comment by fooelisa** [comment]
something is off, looking into it

**Comment by mirceaulinic** [comment]
85℅ is a pretty good score!

**Pull request merged**
